version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: payers
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: payers
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin123
    depends_on:
      - db

volumes:
  postgres_data: {}